# Generated by Django 3.2.12 on 2022-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='producer',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
