# Generated by Django 3.2.12 on 2022-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_playlist_music'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, to='playlist.Playlist'),
        ),
    ]
